### ISSUE TITLE
Allow user to specify MMDevice when initialising WasapiCapture and WasapiLoopbackCapture

### ISSUE THREAD

**Issue by njbmartin** [filoe/cscore#124]
My preview issue #123 raised another potential overload, as both `WasapiCapture` and `WasapiLoopbackCapture` assume the default device should be used.

Currently, you can only change the device after initialising the instance, ~~but even then, it has already been initialised with the default device settings (eg. `WaveFormat`), and you can't change the `WaveFormat`~~. Correction, it's not initialised unless specified in the overload.

So there are few potential things here:

- Add `MMDevice` to the beginning of the overloads and assume that `null` uses default.
- Allow user to customise/change both `Device` and `WaveFormat` after the instance has been initialised.
- Allow a user to modify some properties of `WaveFormat` and apply it to the capture.

**Comment by njbmartin** [comment]
Corrected myself above.

**Comment by filoe** [comment]
It is technically not possible to change to device after WasapiCapture got initialized because the initialization process initializes the devices and sets up all native objects based on this device.
However you can change the device by selecting the device before you call the `Initialize` method. If you change it afterwards, you will have to select to stop capturing and call `Initialize` again. 

I can't add the `MMDevice` to the beginning of the overloads, because it would be modication which makes existing code incompatible with the new release. Maybe I could add this to a new major release. 

Allowing the user to modify some properties of `WaveFormat` is quite tricky. The `WaveFormat` gets choosen by the `Initialize` method. You can't modify it after calling `Initialize`. Anyway, it is not the purpose of a class, implementing the `ISoundIn` interface, to do lots of format conversion. For that purpose, there are existing classes you can use to convert the format to whatever you want. 
You would have to create an `IWaveSource` objects based on the `ISoundIn` objects using the `SoundInSource` class. Afterwards you can use the common conversion extension methods or extra classes. You can do whatever you want. From changing the samplerate to applying a channel conversion matrix, ...

**Comment by njbmartin** [comment]
My apologies, I had a feeling that might be confusing.

Let me explain.

Initialise the object:

```C#
_capture= new WasapiCapture();
```

At this point (before you the `initialize()` method), you can modify the `Device` it uses with:

```C#
_capture.Device = newDevice;
```

But you currently can't specify the `WaveFormat` as it doesn't have a `set` method.

**Comment by filoe** [comment]
Correct, but as I've said before. You can't set the `WaveFormat` because it depends on the driver. `WasapiCapture` chooses a `WaveFormat`, supported by the driver. If you need a specific format, do the conversion outside of `WasapiCapture`.

**Comment by njbmartin** [comment]
Changing the `WaveFormat` mainly relates to my issue raised in #123 in which I needed to modify the channels.

**Comment by filoe** [comment]
That issue already got resolved by overloading the ctor...?

**Comment by njbmartin** [comment]
It did yes, but that assumes the default endpoint is used whereas this issue aims to address the ability to choose any device.

**Comment by filoe** [comment]
What about this code:
```
var captureDevice = MMDeviceEnumerator.EnumerateDevices().First(); //implement your logic for selecting a device...
var deviceFormat = captureDevice.DeviceFormat;
var waveFormat = new WaveFormat(deviceFormat.SampleRate, deviceFormat.BitsPerSample, Math.Min(deviceFormat.Channels, 2));
_wasapiCapture = new WasapiLoopbackCapture(100, waveFormat);
_wasapiCapture.Device = captureDevice;
_wasapiCapture.Initialize();

_wasapiCapture...
```

**Comment by njbmartin** [comment]
Yep, I've used that code too. Alright, guess I'll close this issue then.

**Comment by filoe** [comment]
I've added a tiny sample that should demonstrate the whole thing...
