### ISSUE TITLE
Capture one channel only 

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#134]
I want to play an input device (like the PlayInputDeviceSample) ,But I need to capture ONE channel only. (Left channel only / Right channel only) .

Is this possible ?

Thanks.

**Comment by filoe** [comment]
You can do something like this:
`...

//wrap a sound source around the soundIn instance
//in order to prevent playback interruptions, set FillWithZeros to true
//otherwise, if the SoundIn does not provide enough data, the playback stops
IWaveSource source = new SoundInSource(soundIn) { FillWithZeros = true };

var channelMatrix = ChannelMatrix.StereoToMonoMatrix;
channelMatrix[0, 0].Value = 1; //left channel volume
channelMatrix[1, 0].Value = 0; //right channel volume
source = new DmoChannelResampler(source.ToStereo(), channelMatrix);

//wrap a EchoEffect around the previously created "source"
//note: disposing the echoSource will also dispose 
//the previously created "source"
using (var echoSource = new DmoEchoEffect(source))
...`

**Comment by filoe** [comment]
Can this be closed?

**Comment by Mitra-M** [comment]
Yes of course ,can this be closed.

Using DmoChannelResampler (your above example) the problem is solved.

Previously, I wrote a post here , but I do not know why now erased. (maybe it has been a wrong from my browser)

Anyway,  
Thank you so much
