### ISSUE TITLE
Turn ON/OFF equalizer in realtime

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#142]
I used the PlayInputDeviceSample to play an input device.

Now, I want to turn ON/OFF the equalizer in realtime.

I can do that like this:

        public void playInputDevice(bool EQstate)
        {
          if (EQstate) StopAndClose();   //Close and dispose the WasapiCapture and WasapiOut instances
       ...........
       if (EQstate)
         EffectSource = new BiQuadFilterSource(source.ToSampleSource().AppendSource(Equalizer.Create31BandEqualizer, out _equalizer));

       else 
          EffectSource = new BiQuadFilterSource(source.ToSampleSource());
          ............
         }
, But I can hear a moment of silence when switching on / off  equalizer.

This is possible without causing the silence?

Thanks.

**Comment by filoe** [comment]
An easy but maybe not so clean solution would be using this class instead of the Equalizer class:
```
public class SwitchableEqualizer : Equalizer
{
    public bool Enabled { get; set; }

    public SwitchableEqualizer(ISampleSource source) : base(source)
    {
        Enabled = true;
    }

    public override int Read(float[] buffer, int offset, int count)
    {
        if (Enabled)
        {
            return base.Read(buffer, offset, count);
        }
            
        return BaseSource.Read(buffer, offset, count);
    }
}
```

You would have to create your own `Create10BandEqualizer` method. But you can basically just copy it (actually I'm not really happy with that method at all) or create something on your own.
You could also just add the `Enabled` property to the `Equalizer` class and use it within the `Read` method. For example take a look at this: https://github.com/filoe/cscore/blob/master/CSCore/Streams/Effects/DmoEffectBase.cs#L119

**Comment by Mitra-M** [comment]
Excellent , my problem solved with your solution.

Thank you very much!
