### ISSUE TITLE
ISampleSource.Read without changing Position.

### ISSUE THREAD

**Issue by tjscience** [filoe/cscore#208]
I am trying to read a segment of elements from an ISampleSource but I need to always have the position at 0 and specify my own offset. For some reason, it doesn't seem like this is currently possible.

I have tried to do this with the current method by resetting the position to 0 before each read and it does not work.

This works fine if I simply read all of the elements, store in a float[] and then Array.Copy from there, but as you can imagine, it eats up tons of memory.

**Comment by filoe** [comment]
Do you have some code that reproduces the issue?

**Comment by tjscience** [comment]
I got this to kind of work although it freezes after a couple of seconds. Here is the code I am using:


    public float[] GetDataRange(int start, int length)
        {
            if (start + length > _sampleSource.Length)
                return null;

            var blockSize = length / 1024;
            var samples = new float[1024];

            for (var i = 0; i < 1024; i++)
            {
                var buffer = new float[blockSize];
                _sampleSource.Position = start;
                _sampleSource.Read(buffer, 0, blockSize);
                //Array.Copy(_samples, start, buffer, 0, blockSize);
                var pos = buffer.Where(x => x > 0).ToArray();
                var peakPos = pos.Length > 0 ? pos.Max() : 0;
                samples[i] = peakPos;
                start += blockSize;

            }

            return samples;
        }

**Comment by tjscience** [comment]
Any idea why this is not working?

**Comment by filoe** [comment]
I can't see any lines which could cause a freeze. You should break the debugger and take a look at the different threads where they freezed up the thread.
Anyhow... your code does not make a lot sense.
By reading a certain amount of data the position will be increased by the amount of read data. 
If you additionally seek the source, you'll skip data. Also be aware that sample sources return negative and positive values. So you might use Math.Abs?? Also linq looks nice... but I'm not sure whether it is as fast as a conventional loop.
Also have you took in mind what happens if the length is lower than 1024?

Take a look at the following snipped ... it covers a few of the mentioned points(but not tested!!):
```
public float[] GetDataRange(int start, int length)
{
	if (start + length > _sampleSource.Length)
		return null;

	var blockSize = length / 1024;
	var samples = new float[1024];
	
	_sampleSource.Position = start;
	var buffer = new float[blockSize];
	
	for (var i = 0; i < 1024; i++)
	{
		int read = _sampleSource.Read(buffer, 0, blockSize);
		if(read < buffer.Length)
			Array.Clear(_samples, read, buffer.Length - read);
		var peakPos = _sampleSource.Select(x => Math.Abs(x)).Max();
		samples[i] = peakPos;
	}

	return samples;
}
```

**Comment by tjscience** [comment]
Thanks for the code and suggestions. I will definitely give this a try!

**Comment by tjscience** [comment]
Your code is working much better! My main problem was that I was setting the Position inside of the loop. Thanks!
