### ISSUE TITLE
Some Feature / requests 

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#222]
Hi dear Filoe;
I'd like to greet you for your efforts in such nice Audio library
but as I mentioned in the title, maybe it's already exists but only the lack of documentation is always a big challenge...
Well... First let's start with the file information, I mean here the Channel type of the file, how to get if the IWaveSource or ISampleSource instance is Mono, Stereo etc...? and how to get the Bit Rate (eg. 320 kbps or 128kbps P.S: _source.WaveFormat.BytesPerSecond always gets wrong values) plus the sample rate (44100 KHz, or 22050khz etc)?
2. How to change the Channel pan of IWaveSource or ISampleSource instance that's being played to make only one channel playing and mute the other (eg. Panning to right, or to left).
3. How to make a general Gain effect to the playing _IWaveSource or ISampleSOurce instance (like the Preamp feature in Winamp and other Audio Players).
4. How to get the AudioPeakMeter for the 2 channels of the current IWaveSource or ISampleSource instance that's being played through SoundOut (the example shows only the SoundIn which is not what  need)?
5. The lack of other visualizations like lines with peaks that delays over the lines (like the default one in Winamp), also we need other visualizations like scope one, and eclipse (like those that come with Bass.NET Audio library).
6. I noticed the extreme lack of documentation, indeed I saw the [online one,](http://filoe.github.io/cscore/sharpDox/) but it really adds nothing extra to what I already think it's... There's no explanation, no examples on how to fulfill things nor even how to use the methods, not even mentioned what the methods returns and in case of exceptions what value will be returned?
7. The ID3 section of the library is confusing, especially in the ID3v2, which derives things looks like each other. eg. Header, HeaderFlags, ExtendedHeader, ExtendedHeaderFlag, QuickInfo, as well as CSCore.Tags.ID3.Frames and such things which is not explained at all...
for example, what's the difference between [this](http://filoe.github.io/cscore/sharpDox/1.2.0-release/#type/FrameID) and [this](http://filoe.github.io/cscore/sharpDox/1.2.0-release/#type/ID3v2QuickInfo) - Which one the programmer should rely on?
8. How to update the tags fields in the file? (also how to remove, add or update the image) how to get all images included into the file with its description?) there's no example especially with the confusing sections as mentioned above.
9. How to Record with waveform and visualization? I tried the given sample with the library, but for unknown reason it recorded a file that's only 1 second length then it stops, even this one second file is not playable at all. so any real-life example with applying effects (like echo, Equalizer and Boosted mic) would be highly appreciated.

Please take your time to read and answer, as I tried for many weeks to find solutions for such points but in vain, so I would appreciate the detailed answers from you. Thanks in advance.     - Bahaa.

**Comment by tjscience** [comment]
In addition to what @Mitra-M has mentioned, it is outside of the scope of cscore to provide built in visualizations. There are examples in the project that show you how to do this, but they are just that, examples. You either need to roll your own or use a library like the one that I am currently developing, [audion](https://github.com/tjscience/audion), to accomplish this.

**Comment by Bahaatya** [comment]
@Mitra-M -1 for judging the book from its cover/title!

> I think it is better to search more carefully.

 - Back to you as well...

well... I've already read [#134](https://github.com/filoe/cscore/issues/134), and didn't get that the verb "Capture" meant to say "pan", also I noticed that Mr. Filoe answered you in that question using 

> var channelMatrix = ChannelMatrix.StereoToMonoMatrix;

which means also it converts the 2 channel to be in 1 output channel (Mono) which is not what I meant nor wanted.
Also I don't use Channel Matrix object, instead I have A ISoundOut that waits for ISampleSource to be converted at a stage of the program as IWaveSource to play it... and I want to keep the two channels separated as they are (Stereo).
Also his answer was giving a full left channel and full right channel example....

> channelMatrix[0, 0].Value = 1; //left channel volume
> channelMatrix[1, 0].Value = 0; //right channel volume

so what about when you want to pan a percentage to left or to right using a panning slider/ticker control, not full?

As for [#155](https://github.com/filoe/cscore/issues/155) I noticed that Filoe answered with SoundIn
saying: 

> using (var soundIn = new WasapiCapture(true, AudioClientShareMode.Shared, 30))

which I understood it meant to capture the Master sound of the Sound Card, that will also capture the sound of other apps being working?
and as I mentioned above that I have ISoundOut... so this what confuses me, and that's why I asked such question.

generally thanks for your time and efforts to help... still I'll not consider it as null... I appreciate it.

As for  @tjscience I would like to thank you so much for your reply as well... but this what I was talking about A "Documentation" what if there's a documentation that says what the CSCore is concerning for? As I understood from the few words that introduce the library that it has this feature (which makes you feel it's not just example) and made me hope there's more, like the case with Bass.NET Audio Library that provides you with several visualizations...
I think that a Programmer loves when users show interest in his product/library, ask him how to do things and seek for more... it gives him a push to forward and motivation!

Thanks a  lot for both of you... 

Still waiting for any useful answer from users, which will be highly appreciated.

**Comment by Mitra-M** [comment]
My language is not English. Sorry for my bad English.

There are at least two feature for pan a percentage to left or to right in the cscore.

1 - DmoChannelResampler class
Which as I said before . ( #134 )

2 - PanSource class
you can use the PanSource like this:

 `    WasapiCapture soundIn;
        WasapiOut soundOut;
        PanSource pan;
     . . . . . . 
   trackBar1.ValueChanged += TrackBar1_ValueChanged;
     . . . . .

            soundIn = new WasapiCapture(true, AudioClientShareMode.Shared, 30);
            soundIn.Initialize();
            IWaveSource source = new SoundInSource(soundIn) { FillWithZeros = true };
            soundIn.Start();
            soundOut = new WasapiOut();
            pan = new PanSource(source.ToSampleSource().ToStereo());
            soundOut.Initialize(pan.ToWaveSource());
            soundOut.Play();
            . . . . .         
        private void TrackBar1_ValueChanged(object sender, EventArgs e)
        {
            pan.Pan = trackBar1.Value; // should be :  >=0  trackBar1.Value  <=1
        }`


You can use the AudioPeakMeter  for both SoundIn /SoundOut .

If your source is a file , you should use this:
`  using (var source = CodecFactory.Instance.GetCodec(openFileDialog.FileName))`

instead of `using (var soundIn = new WasapiCapture(true, AudioClientShareMode.Shared, 30))`

**Comment by filoe** [comment]
1. This library is not a tab or media information library on it's primary. Of course, you can get informations like number of channels which is essential. The WaveFormat property of every IWaveSource and ISampleSource will provide such information. See Channels property. Depending on the implementation and input of the Source objects, the WaveFormat object is of type WaveFormatExtensible which provides a ChannelMask which tells you which channels are present (mainly used in multichannel scenarios).
2. There is the PanSource and the DmoChannelResampler. I would suggest using the DmoChannelResampler (as already mentioned in this issue).
3. There is the GainSource class, you can use for that. 
4. The example is also capable for SoundOut. Adopt to your needs. The processing of Source objects follows always the same way. For SoundIn you have to pull data through the Source objects yourself, for SoundOut, it is done by the implementation of the SoundOut (e.g. WasapiOut). Build a source chain and initialize the soundout with it.
5. The core components of cscore do not contain visualizations since I don't want to make references to any graphic components. There are a few quite rich examples on how to visualize audio. The rendering of the visualizations of some peaks or whatever is up to you.
6. Well, to cover all things to notice, I could write a book. This is and always was an open source project. It is done in my rare freetime. All public components are documented using the xml doc. There are enough samples and unit tests which demonstrate the basic usage and even some advanced stuff. You can also always feel free to ask, opening a issue and I'll give you an answer as soon as I can (again: it's an open source project). If you want so, you're welcome to contribute yourself.
7. As already said, the primary purpose of this library is not reading out tags. ID3v2 is a relict, which could be stated more clearly (it was mentioned in some issues). 
8. Not supported.
9. The recording example demonstrates loopback recording and microphone recording. If there is no sound played on your system, it won't record anything (the stream won't be filled up with zeros). 
You can set this const to Capture (see https://github.com/filoe/cscore/blob/master/Samples/Recorder/MainWindow.cs#L17).
The example demonstrates how to build up a source chain from an input device. See https://github.com/filoe/cscore/blob/master/Samples/Recorder/MainWindow.cs#L76 and following. 
You can easily add an equalizer or what ever yourself.
