### ISSUE TITLE
Stream reads beyond length

### ISSUE THREAD

**Issue by Noxygen** [filoe/cscore#267]
It appears that a SampleProvider can read more data than the file provides resulting in random data being attached to the buffer.

One example with a 24 bit wave file, loaded using GetCodec(), converted to a samplesource and back for playback:
Stream length: 371804 samples
Position before read: 371512
Requested: 1920
read: 317
.. resulting in the final pointer position of 371829 wich adds 17 random samples to the buffer and can clearly be heard as a loud crackle.

Due to the lack of time I haven't yet figured out an easy way to reproduce this bug but I hope it's still worth to take a look at. The current workaround of course is to manually check the avaiable amount of data before calling Read().
![screen](https://user-images.githubusercontent.com/2007411/29744710-351e3684-8aab-11e7-9b47-52995e2cb984.png)

**Comment by filoe** [comment]
Sorry for the very late response.
Which decoder is returned by GetCodec?
Is it the WaveFileDecoder, any MediaFoundationDecoder or even the ffmpeg decoder?

**Comment by Noxygen** [comment]
I took some time and finally found a way to reproduce the error and provide you an example application + wave sample.
Hope it gives you all the information you need.
[TestConsole.zip](https://github.com/filoe/cscore/files/1290139/TestConsole.zip)

**Comment by filoe** [comment]
You've added the following check:
`Debug.Assert(Source.Position < Source.Length);`
It seems to be correct. But in fact it is slightly more complicated than it seems.

We've got some decoders like the `MediaFoundationDecoder` which may return an unaccurate length (see https://github.com/filoe/cscore/blob/master/CSCore/MediaFoundation/MediaFoundationDecoder.cs#L311).

If you really want an absolutely accurate length, you have to decode the whole file and count the number of bytes.

Maybe your issue was connected to #270. 
I could not hear any noise anymore. Just try it out once again with the current version of the master branch. Or wait until I publish the next nuget package.

**Comment by Noxygen** [comment]
Yep the noise is gone. 
Now what is the proper way to handle wav samples? Or should I just parse the DATA chunk manually?

**Comment by filoe** [comment]
Why should you handle any chunks manually?

**Comment by Noxygen** [comment]
The returned length is wrong, so what should I do to get a correct value?

**Comment by Noxygen** [comment]
Ok, seems like I got it to work now. 
Thanks for the fix!
