### ISSUE TITLE
Analyze file and get FftData from timeStamp

### ISSUE THREAD

**Issue by Capplequoppe** [filoe/cscore#273]
Hi!

Im trying to write a web application that analyzes audio.
Currently i do realtime visualisation by Javascript on the FrontEnd,
but for more performance reasons I want to do some analysis on the server.
A wave file is uploaded to the server.
I then want to get fft values for specific timestamps without the need to actually playing the file, how do i do that?

Can I achieve this by the following pseudo code, and if so how do i write it?

```
var startMillisecond = 0;
var endMillisecond = 3000;
var stepMillisecond = 5;
var fftBuffer = new float[4096]; //(or some other fftSize)

for (int i = startMillisecond; i <endMillisecond; i += stepMillisecond)
{
   FillFftBufferAtThisTimestamp(i);
   ProcessFftData();
}

```

**Comment by filoe** [comment]
Of course you do not have to play the file first.
What you still have to do is decoding the file and run the fft analyse.
You can refer to the WinformsVisualization sample for the setup.
Instead of playing the audio (https://github.com/filoe/cscore/blob/master/Samples/WinformsVisualization/Form1.cs#L55)
seek to the correct timestamp (use the Position property of the `_source` or the SetPosition extension ... see https://github.com/filoe/cscore/blob/master/CSCore/Extensions.cs#L48) and call its `Read`-method manually to process data.

For example:
Note: just written in notepad. Please adjust it yourself. 
Also make sure to `Dispose` source as soon as you don't need it anymore.
```
var source = CodecFactory.Instance.GetCodec("any-file.wav")
	.ToSampleSource();
	
var fftProvider = new FftProvider(source.WaveFormat.Channels, FftSize.Fft2048);
	
source.SetPosition(TimeSpan.FromSeconds(...)); //seek

TimeSpan length = TimeSpan.FromSeconds(1); //analyse one second

int lengthInSamples = source.GetRawElements(length);
int maxBufferLengthInSamples = 2048; //for fftsize 2048, always a block of 2048 samples will be analysed

int bufferLength = Math.Min(lengthInSamples, maxBufferLengthInSamples);
	
float[] buffer = new float[bufferLength];

int read = 0;
int totalSamplesRead = 0;

var fftData = new float[2048];
//var fftData = new Complex[2048]; //use complex numbers if needed

do
{
	//determine how many samples to read
	int samplesToRead = Math.Min(lengthInSamples - totalSamplesRead, buffer.Length);

	read = source.Read(buffer, 0, samplesToRead);
	if(read == 0)
	{
		//we've hit the end of the stream
		break;
	}
	totalSamplesRead += read;
	
	//add read data to the fftProvider
	fftProvider.Add(buffer, read);
	
	fftProvider.GetFftData(fftData);
	
	//process fftData ...
	foreach(var fftDataPoint in fftData)
	{
		...
	}
}
while(totalSamplesRead < lengthInSamples);
```
