### ISSUE TITLE
What is the recommended way to play a file from ISoundOut.Stopped

### ISSUE THREAD

**Issue by SamuelCox** [filoe/cscore#290]
Currently I have code where ISoundOut.Stopped makes a call to intialize and play, this throws because of the "you cannot call this method from the playback thread". What is the recommended way to do this? Currently I just do ThreadPool.QueueUserWorkItem for the method instead, which works, but feels weird.

**Comment by filoe** [comment]
The problem is quite simple:
Inside of most of the `SoundOut` implementations is running a seperate `Thread` which processes your audio source and feeds the audio driver with new data.
If this `Thread` stops, the implementation raises the `Stopped` event but still inside of the `Thread`.
The `Initialize` or `Play` method will wait until that `Thread` is stopped (since it releases resources and stuff).
If you call those methods from within that `Thread` you'll have a deadlock. Because you force the playback `Thread` to wait until itself has stopped which will never occur.
Therefore the `Exception` is thrown.

**Comment by SamuelCox** [comment]
I appreciate the explanation, thanks, but I was more asking if there was any part of cscore that would do the call on the original thread rather than the playback thread for me. Admittedly, that seems like it would be quite a weird thing to build in. I'm happy enough just to use the solution I have at the moment though.

**Comment by filoe** [comment]
There is currently no such thing.
If you are on winforms you can use Control.Invoke or on WPF the dispatchers Invoke method.
On other platforms, you have to build your own logic.

**Comment by SamuelCox** [comment]
Dispatcher should work for me actually, completely forgot about that. Thanks very much for the help.
