### ISSUE TITLE
Ffmpeg - doesn't release the locked file until the program is stopped

### ISSUE THREAD

**Issue by eklam** [filoe/cscore#294]
Running the sample program **FfmpegSample** if you place a breakpoint after the `FfmpegDecoder`. You may not change/delete the file, since it's still being used by another process. Is there any workaround for this issue?

**Comment by filoe** [comment]
Thanks for reporting. 
Since Ffmpeg in CSCore is quite new, there might be a few minor issues. I'll fix it!

**Comment by eklam** [comment]
Great , do you think this will be a quick fix?

I am trying to delete the file after the fact, if the fix will take time I'll likely rework my workflow so the files are deleted another time (likely after the program is restarted).

Thanks for the reply

**Comment by filoe** [comment]
Sorry for the late response.
It is no issue in CSCore.Ffmpeg. Is is just an issue in the FfmpegSample. 
To demonstrate the usage of `Stream`, the FfmpegSample passes a `FileStream` to the `FfmpegDecoder`.
The decoder won't close the stream on itself (since it did not allocate it).
You have to close the stream yourself or pass the filename as string (url parameter).
See https://github.com/filoe/cscore/blob/d72a1d3e1f47b15c0c26d81c5deb93607a9ac2a6/Samples/FfmpegSample/Program.cs#L66.
