### ISSUE TITLE
FfmpegEncode

### ISSUE THREAD

**Issue by Lutando** [filoe/cscore#320]
Is there an ability to encode using Ffmpeg? Had a look over the repository and found no obvious way on how this can be done?

**Comment by filoe** [comment]
I'm sorry for the late response.
No currently there is no way to encode audio. I've started implementing it a while ago. But I had no time to finish it. Should not be a big deal, since all interop methods are already declared. 
But again, currently I do not have the time to implement it. 
If you want to implement it yourself, you can count on my help.
