### ISSUE TITLE
[Question] Can’t close app while sound is playing

### ISSUE THREAD

**Issue by steam3d** [filoe/cscore#411]
I learn this example  [AudioPlayerSample](https://github.com/filoe/cscore/tree/master/Samples/AudioPlayerSample)

I set the source mp3 file and play it.
`_musicPlayer.play()`

While music is playing I click close window button. Window closed, but music still playing. Only when music ended the app is completely closed.

How do I fix this?

**Comment by filoe** [comment]
You have to stop the soundOut instance and dispose it in order to close the process completely.

Most soundOut providers are running background threads.

 

Von: Alexander Maslov <notifications@github.com> 
Gesendet: Donnerstag, 30. April 2020 20:20
An: filoe/cscore <cscore@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [filoe/cscore] [Question] Can’t close all while sound is playing (#411)

 

I learn this example AudioPlayerSample <https://github.com/filoe/cscore/tree/master/Samples/AudioPlayerSample> 

I set the source mp3 file and play it.
_musicPlayer.play()

While music is playing I click close window button. Window closed, but music still playing. Only when music ended the app is completely closed.

How do I fix this?
