### ISSUE TITLE
Trying to understand how to open a Wasapi device if I already know the friendly name or device id

### ISSUE THREAD

**Issue by ToxMox** [filoe/cscore#427]
How would I go about setting a Wasapi device based on its Device ID?
For example my device id for a specific audio device is {0.0.1.00000000}.{bddbb7cc-a684-4668-ac06-23c2a059ed03}
In the snippet of code below I'm able to activate the default microphone. Any idea how would I adjust this code to force the device above?

```
                    MMDevice defaultMicrophone;
                    DeviceId = deviceId;
                    using (var deviceEnumerator = new MMDeviceEnumerator())
                    {
                        defaultMicrophone = deviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Capture, Role.Communications);
                      }
                    _wasapiCapture = new WasapiCapture();
                    _wasapiCapture.Device = defaultMicrophone;
```

**Comment by filoe** [comment]
Use the `MMDeviceEnumerator` to enumerate all capture devices instead of just the default one. The returned devices all have some properties including their `DeviceId`. Choose the wanted device based on the `DeviceId` and pass it to the `Device` property of the `WasapiCapture` instance as you already done.

**Comment by ToxMox** [comment]
Thank you that helped!
