### ISSUE TITLE
Audio threads running as Foreground threads

### ISSUE THREAD

**Issue by cmdrmcdonald** [filoe/cscore#45]
It appears that the audio threads in CSCore are running as Foreground threads, which means that if I have a long-running WasapiOut() running then I can't close the parent process until Play() has finished.

Would it be possible to make the threads Background threads, or at least expose the ability for users to choose to do so, so that they die when the parent process is killed?

**Comment by filoe** [comment]
The reason is that the uncontrolled aborting of Playbackthreads can cause unwanted behaviour what releasing resources concerns.

**Comment by cmdrmcdonald** [comment]
Does this mean that I have to avoid sending an Abort() to the cscore threads and instead close them down using IWaveOut.Stop()?

**Comment by filoe** [comment]
Your exactly right. Aborting Threads is always a sign of some kind of bad architecture. In order to release all allocated resources, cscore tries to exit threads by setting flags. So if your application exists, just make sure to dispose the SoundOut instances (and all other objets like IWaveSource objects,..)
