### ISSUE TITLE
Audio pitch shifter with CSCore

### ISSUE THREAD

**Issue by postacik** [filoe/cscore#57]
Hi,

I added an article about my audio pitch shifter application to CodeProject which uses CSCore.

Can you please review it and return with your valuable suggestions?

http://www.codeproject.com/Tips/1082074/Audio-Pitch-Shifter

**Comment by filoe** [comment]
That's a very nice project. Since I'm always wanted to try out some audio pitch shifting stuff using CSCore, I'm glad you've used CSCore!

Without digging deep into the code, I can't tell you anything about the DSP-Effect itself. But it looks quite solid. Your code applies the basic principles of CSCore perfectly. There is only one point I don't really understand. Some applications(for example spotify) can't really deal with other apps using exclusive-playback. Although, it can be a powerful feature, I would be careful with it(you may add another checkbox?). Also the mMp3 is not getting disposed correctly.

It would be also great to just be able to play a file with the pitch shifting effect applied to it. 

But all in all, I love to see your article. Keep up your work!

**Comment by postacik** [comment]
Thanks for your comments and your valuable CSCore library.
