### ISSUE TITLE
How to separate sources for drawing and playing wave

### ISSUE THREAD

**Issue by postacik** [filoe/cscore#64]
I am working on a wave editor which uses CSCore to read and play music files.

I initialize my source as the following:

```c#
            mSoundSource = CodecFactory.Instance.GetCodec(fileName).ToSampleSource().ToMono();
            mWaveSource = mSoundSource.ToWaveSource(16);
            mMusicPlayer.Open(mWaveSource, device);
```

To draw wave form of the audio file I set mSoundSource.Position to some offset and read audio data starting from that offset.

If I change the mSoundSource.Position while audio is playing, playing position is also changed since mWaveSource is linked to mSoundSource.

What is the most effective wave of separating sources for "drawing wave form" and "playing audio"?

**Comment by filoe** [comment]
You've got several options:

1. Open the file twice. This option consumes a bit more performance, since you decode it once for the Waveform and once for the playback. But the performance impact should be still faaaar away from any critical level.

2. Decode the file to a temporary file and implement some kind of "thread-static"-decoder which its own position for each thread. If WasapiOut would call the read method it would read data at the playback position. If the Waveform calls the read method it would read data from its current read-position. 

3. Implement the same principle as described in 2. but store the decoded data in the memory. You may would have to extend the CachedSoundSource class. For large files, this can consume quite a lot memory. But an average file, it should not be any problem.

**Comment by postacik** [comment]
Thanks, I'll try one of them.
